# Generated by Django 3.2.5 on 2021-07-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10, unique=True)),
                ('user_id', models.CharField(max_length=32, unique=True)),
                ('user_pw', models.CharField(max_length=128)),
                ('user_created', models.DateTimeField(auto_now_add=True)),
                ('user_subjects', models.TextField(null=True)),
            ],
            options={
                'ordering': ['user_created'],
            },
        ),
    ]
